name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  Build:
    name: Build
    runs-on: macOS-latest
    defaults:
      run:
        shell: bash
        working-directory: ui/espresso/ScreenshotSample
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 11
      - uses: malinskiy/action-android/install-sdk@release/0.1.4
      - run: sdkmanager platform-tools
      - run: ./gradlew assembleDebug nexusOneApi30DebugAndroidTest
